### ISSUE TITLE
Testing skosprovider_atramhasis based on atramhasis services

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/skosprovider_atramhasis#3]
Currently the tests use the atramhasis-services (running on localhost:6543). Which strategy are we going to use here: Mocking the atramhasis services OR using atramhasis services that are deployed on a dev/test-environment?

**Comment by koenedaele** [comment]
Since the unit tests should be able to run on Travis and we haven't got a stable, public version of Atramhasis running somewhere that it can be reached, I think we've got only two options:

* Mock the services.
* Run a version of pyramid_skosprovider during the unit tests as some sort of mock server. We once did something similar in our authentication library. But as I recall this caused more problems after a while.

So I think our best bet would be to mock the service or monkeypatch the requests or something similar

@BartSaelen I think you're the most qualified to handle this kind of problem. Your opinion?

**Comment by BartSaelen** [comment]
I think mocking the services is the best option here. Since communication to the services is based upon 'requests', I think we can use https://github.com/dropbox/responses for this. I've used this before and works quite well.

**Comment by koenedaele** [comment]
Ok, seems like a good solution. Who's taking care of this?

**Comment by dieuska** [comment]
I'll do that tomorrow so the tests can succeed on travis!
